[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "virustotal-scanner-gui"
version = "1.0.0"
description = "Eine lokale GUI-Anwendung zum Scannen von Dateien über die VirusTotal API"
authors = ["Thorsten Bylicki <bylicki@mail.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bylickilabs/virustotal-scanner"
repository = "https://github.com/bylickilabs/virustotal-scanner"
documentation = "https://github.com/bylickilabs/virustotal-scanner/wiki"
keywords = ["VirusTotal", "Scanner", "Sicherheit", "Hash", "GUI"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
PySimpleGUI = "^4.60.5"
python-dotenv = "^1.0.1"
tqdm = "^4.66.1"
babel = "^2.14.0"
qrcode = "^7.4.2"
Pillow = "^10.3.0"

[tool.poetry.scripts]
vt-scanner = "virustotal_scanner_gui.app:main"